# Generated by Django 4.2.7 on 2025-04-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_farmstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmstatus',
            name='status_image',
            field=models.FileField(blank=True, null=True, upload_to='farm_status_images'),
        ),
    ]
