# Generated by Django 4.2.7 on 2025-05-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0003_farmstatus_status_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmstatus',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
