# Generated by Django 4.2.7 on 2025-05-13 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0004_farmstatus_pinned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmstatus',
            old_name='pinned',
            new_name='is_pinned',
        ),
    ]
