# Generated by Django 4.2.7 on 2025-05-13 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0005_rename_pinned_farmstatus_is_pinned'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmstatus',
            options={'ordering': ['-is_pinned', '-date']},
        ),
    ]
