# Generated by Django 4.2.7 on 2025-04-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expert', '0002_framemercheckout'),
    ]

    operations = [
        migrations.AddField(
            model_name='framemercheckout',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
