# Generated by Django 4.2.7 on 2025-04-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expert', '0003_framemercheckout_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='framemercheckout',
            name='delivery_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='framemercheckout',
            name='delivery_service',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='framemercheckout',
            name='delivery_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='framemercheckout',
            name='estimated_delivery',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='framemercheckout',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
